In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [11]:
img = cv2.imread(r"Screenshot (9).png")

In [13]:
print(img)

[[[249 243 240]
  [249 243 240]
  [249 243 240]
  ...
  [249 244 240]
  [249 244 240]
  [249 244 240]]

 [[249 243 240]
  [249 243 240]
  [249 243 240]
  ...
  [249 244 240]
  [249 244 240]
  [249 244 240]]

 [[249 243 240]
  [249 243 240]
  [249 243 240]
  ...
  [249 244 240]
  [249 244 240]
  [249 244 240]]

 ...

 [[ 44  34  29]
  [ 44  34  29]
  [ 45  35  30]
  ...
  [ 41  34  30]
  [ 39  32  28]
  [ 39  32  28]]

 [[ 45  35  30]
  [ 42  32  27]
  [ 43  33  28]
  ...
  [ 40  33  29]
  [ 40  33  29]
  [ 41  34  30]]

 [[ 44  34  29]
  [ 45  35  30]
  [ 44  34  29]
  ...
  [ 42  35  31]
  [ 41  34  30]
  [ 40  33  29]]]


In [15]:
print(type(img))

<class 'numpy.ndarray'>


In [17]:
cv2.imshow("imgg",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
print(img.shape)

(1080, 1920, 3)


In [21]:
img_resize = cv2.resize(img,(203,300))

In [23]:
img_resize

array([[[249, 243, 240],
        [249, 243, 240],
        [249, 243, 240],
        ...,
        [249, 244, 240],
        [249, 244, 240],
        [249, 244, 240]],

       [[145,  94,  94],
        [156, 110, 110],
        [249, 243, 240],
        ...,
        [249, 244, 240],
        [249, 244, 240],
        [249, 244, 240]],

       [[214, 204, 204],
        [207, 199, 198],
        [249, 243, 240],
        ...,
        [249, 244, 240],
        [249, 244, 240],
        [249, 244, 240]],

       ...,

       [[ 43,  33,  28],
        [ 43,  33,  28],
        [ 44,  34,  29],
        ...,
        [ 41,  34,  30],
        [ 40,  33,  29],
        [ 41,  34,  30]],

       [[ 42,  32,  27],
        [ 43,  33,  28],
        [ 43,  33,  28],
        ...,
        [ 39,  32,  29],
        [ 41,  34,  30],
        [ 41,  34,  30]],

       [[ 42,  32,  27],
        [ 45,  35,  30],
        [ 43,  33,  28],
        ...,
        [ 41,  34,  30],
        [ 40,  33,  29],
        [ 40,  33,  29]]

In [25]:
cv2.imshow("manya",img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
print(img_resize.shape)

(300, 203, 3)


In [31]:
img_flip = cv2.flip(img,1)

In [33]:
cv2.imshow("flipped Image",img_flip)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [35]:
img_crop = img[100:300,200:500]

In [37]:
cv2.imshow("Cropped Image",img_crop)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:
cv2.imwrite(r"croppedImg16.jpg",img_crop)

True